services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toll-roads-api
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./:/app/
    command: python manage.py runserver 0.0.0.0:${API_PORT}

  adminer:
    image: adminer
    container_name: toll-roads-adminer
    restart: always
    depends_on:
      - postgres
    environment:
      - ADMINER_DESIGN=dracula
    ports:
      - ${ADMINER_PORT}:8080

  postgres:
    image: postgres:latest
    container_name: toll-roads-postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: toll-roads-redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis-data:/data


networks:
  postgres-data:
  redis-data: