# Generated by Django 5.1.1 on 2024-10-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(db_index=True, max_length=75, unique=True),
        ),
    ]
