# Generated by Django 5.1.3 on 2024-11-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="tokens",
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
